# Generated by Django 5.2 on 2025-05-05 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="analysisrun",
            name="user_video",
        ),
        migrations.AddField(
            model_name="analysisrun",
            name="video",
            field=models.FileField(
                default=datetime.time(11, 29, 1, 890418),
                max_length=200,
                upload_to="video/",
            ),
            preserve_default=False,
        ),
    ]
